version: '3.9'
services:

  postgresServer:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./testFolder:/usr/src/app
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
