version: '3.9'
services:
  dbPostgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: taskmanagement

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
